Repository uasoft-indonesia/badaso-posty-theme, pull requests merged in 2021-08, with the labels that each got.

#19 Apply fixes from StyleCI
  src/Providers/PostThemeProvider.php
  src/Seeder/PostThemeConfigurationsSeeder.php
  src/Seeder/PostThemeContentsSeeder.php
  src/Seeder/PostThemeFixedMenuItemSeeder.php
  src/Seeder/PostThemeMenusSeeder.php
  src/Seeder/PostThemePermissionsSeeder.php
Labels: backend

#21 Apply fixes from StyleCI
  src/Seeder/BadasoPostThemeSeeder.php
  src/Seeder/PostThemeConfigurationsSeeder.php
  src/Seeder/PostThemeContentsSeeder.php
  src/Seeder/PostThemeFixedMenuItemSeeder.php
  src/Seeder/PostThemeMenusSeeder.php
  src/Seeder/PostThemePermissionsSeeder.php
Labels: backend

#20 Update post theme for 1.x
  README.md
  composer.json
  src/Commands/PostThemeSetup.php
  src/Images/facebook.svg
  src/Images/instagram.svg
  src/Images/telegram.svg
  src/Images/twitter.svg
  src/Images/youtube.svg
  src/Providers/PostThemeProvider.php
  src/Routes/web.php
  src/Seeder/BadasoPostThemeSeeder.php
  src/Seeder/PostThemeConfigurationsSeeder.php
  src/Seeder/PostThemeContentsSeeder.php
  src/Seeder/PostThemeFixedMenuItemSeeder.php
  src/Seeder/PostThemeMenusSeeder.php
  src/Seeder/PostThemePermissionsSeeder.php
  src/resources/js/api/index.js
  src/resources/js/app.js
  src/resources/js/assets/images/facebook.png
  src/resources/js/assets/images/facebook.svg
  src/resources/js/assets/images/google.png
  src/resources/js/assets/images/instagram.png
  src/resources/js/assets/images/instagram.svg
  src/resources/js/assets/images/path.png
  src/resources/js/assets/images/skype.png
  src/resources/js/assets/images/telegram.png
  src/resources/js/assets/images/telegram.svg
  src/resources/js/assets/images/twitter.png
  src/resources/js/assets/images/twitter.svg
  src/resources/js/assets/images/vimeo.png
  src/resources/js/assets/images/youtube.png
  src/resources/js/assets/images/youtube.svg
  src/resources/js/assets/scss/_custom.scss
  src/resources/js/components/category-type-one.vue
  src/resources/js/components/category-type-two.vue
  src/resources/js/components/category.vue
  src/resources/js/components/comment.vue
  src/resources/js/components/footer.vue
  src/resources/js/components/home.vue
  src/resources/js/components/index.js
  src/resources/js/components/navbar.vue
  src/resources/js/components/newest-post.vue
  src/resources/js/components/newest.vue
  src/resources/js/components/other.vue
  src/resources/js/components/popular-post.vue
  src/resources/js/components/popular.vue
  src/resources/js/components/post.vue
  src/resources/js/components/search.vue
  src/resources/js/lang/index.js
  src/resources/js/lang/modules/en.js
  src/resources/js/lang/modules/id.js
  src/resources/js/pages/configuration/browse.vue
  src/resources/js/pages/index.vue
  src/resources/js/router/excludeRouter.js
  src/resources/js/router/routes.js
  src/resources/js/store/badaso.js
  src/resources/js/store/store.js
  src/resources/views/category.blade.php
  src/resources/views/errors/404.blade.php
Labels: frontend, backend, dependencies, feature

#13 Add laravel 8 support
  README.md
  composer.json
  src/Commands/PostThemeSetup.php
  src/Images/facebook.svg
  src/Images/instagram.svg
  src/Images/telegram.svg
  src/Images/twitter.svg
  src/Images/youtube.svg
  src/Providers/PostThemeProvider.php
  src/Routes/web.php
  src/Seeder/BadasoPostThemeSeeder.php
  src/Seeder/PostThemeConfigurationsSeeder.php
  src/Seeder/PostThemeContentsSeeder.php
  src/Seeder/PostThemeFixedMenuItemSeeder.php
  src/Seeder/PostThemeMenusSeeder.php
  src/Seeder/PostThemePermissionsSeeder.php
  src/resources/js/api/index.js
  src/resources/js/app.js
  src/resources/js/assets/images/facebook.png
  src/resources/js/assets/images/facebook.svg
  src/resources/js/assets/images/google.png
  src/resources/js/assets/images/instagram.png
  src/resources/js/assets/images/instagram.svg
  src/resources/js/assets/images/path.png
  src/resources/js/assets/images/skype.png
  src/resources/js/assets/images/telegram.png
  src/resources/js/assets/images/telegram.svg
  src/resources/js/assets/images/twitter.png
  src/resources/js/assets/images/twitter.svg
  src/resources/js/assets/images/vimeo.png
  src/resources/js/assets/images/youtube.png
  src/resources/js/assets/images/youtube.svg
  src/resources/js/assets/scss/_custom.scss
  src/resources/js/components/category-type-one.vue
  src/resources/js/components/category-type-two.vue
  src/resources/js/components/category.vue
  src/resources/js/components/comment.vue
  src/resources/js/components/footer.vue
  src/resources/js/components/home.vue
  src/resources/js/components/index.js
  src/resources/js/components/navbar.vue
  src/resources/js/components/newest-post.vue
  src/resources/js/components/newest.vue
  src/resources/js/components/other.vue
  src/resources/js/components/popular-post.vue
  src/resources/js/components/popular.vue
  src/resources/js/components/post.vue
  src/resources/js/components/search.vue
  src/resources/js/lang/index.js
  src/resources/js/lang/modules/en.js
  src/resources/js/lang/modules/id.js
  src/resources/js/pages/configuration/browse.vue
  src/resources/js/pages/index.vue
  src/resources/js/router/excludeRouter.js
  src/resources/js/router/routes.js
  src/resources/js/store/badaso.js
  src/resources/js/store/store.js
  src/resources/views/category.blade.php
  src/resources/views/errors/404.blade.php
Labels: frontend, backend, dependencies, feature

#22 Prepare nex release
  README.md
  composer.json
  src/Commands/PostThemeSetup.php
  src/Images/facebook.svg
  src/Images/instagram.svg
  src/Images/telegram.svg
  src/Images/twitter.svg
  src/Images/youtube.svg
  src/Providers/PostThemeProvider.php
  src/Routes/web.php
  src/Seeder/BadasoPostThemeSeeder.php
  src/Seeder/PostThemeConfigurationsSeeder.php
  src/Seeder/PostThemeContentsSeeder.php
  src/Seeder/PostThemeFixedMenuItemSeeder.php
  src/Seeder/PostThemeMenusSeeder.php
  src/Seeder/PostThemePermissionsSeeder.php
  src/resources/js/api/index.js
  src/resources/js/app.js
  src/resources/js/assets/images/facebook.png
  src/resources/js/assets/images/facebook.svg
  src/resources/js/assets/images/google.png
  src/resources/js/assets/images/instagram.png
  src/resources/js/assets/images/instagram.svg
  src/resources/js/assets/images/path.png
  src/resources/js/assets/images/skype.png
  src/resources/js/assets/images/telegram.png
  src/resources/js/assets/images/telegram.svg
  src/resources/js/assets/images/twitter.png
  src/resources/js/assets/images/twitter.svg
  src/resources/js/assets/images/vimeo.png
  src/resources/js/assets/images/youtube.png
  src/resources/js/assets/images/youtube.svg
  src/resources/js/assets/scss/_custom.scss
  src/resources/js/components/category-type-one.vue
  src/resources/js/components/category-type-two.vue
  src/resources/js/components/category.vue
  src/resources/js/components/comment.vue
  src/resources/js/components/footer.vue
  src/resources/js/components/home.vue
  src/resources/js/components/index.js
  src/resources/js/components/navbar.vue
  src/resources/js/components/newest-post.vue
  src/resources/js/components/newest.vue
  src/resources/js/components/other.vue
  src/resources/js/components/popular-post.vue
  src/resources/js/components/popular.vue
  src/resources/js/components/post.vue
  src/resources/js/components/search.vue
  src/resources/js/lang/index.js
  src/resources/js/lang/modules/en.js
  src/resources/js/lang/modules/id.js
  src/resources/js/pages/configuration/browse.vue
  src/resources/js/pages/index.vue
  src/resources/js/router/excludeRouter.js
  src/resources/js/router/routes.js
  src/resources/js/store/badaso.js
  src/resources/js/store/store.js
  src/resources/views/category.blade.php
  src/resources/views/errors/404.blade.php
Labels: frontend, backend, dependencies

#23 Bump to 2.0.0-rc
  composer.json
Labels: dependencies

#24 Fix badasoBlog on store
  src/resources/js/store/store.js
Labels: frontend, bugfix

#25 Prepare next release
  src/resources/js/store/store.js
Labels: frontend

#27 Fix installation
  src/Commands/PostThemeSetup.php
  src/resources/js/app.js
  src/resources/js/assets/scss/style.scss
  src/resources/views/layouts/default.blade.php
Labels: frontend, backend, bugfix

#26 Fix installation
  src/Commands/PostThemeSetup.php
  src/resources/js/app.js
  src/resources/js/assets/scss/style.scss
  src/resources/views/layouts/default.blade.php
Labels: frontend, backend, bugfix

#28 Prepare next release
  src/Commands/PostThemeSetup.php
  src/resources/js/app.js
  src/resources/js/assets/scss/style.scss
  src/resources/views/layouts/default.blade.php
Labels: frontend, backend

#30 Fix value undefined on load
  src/resources/js/app.js
Labels: frontend, bugfix

#29 Fix value undefined on load
  src/resources/js/app.js
Labels: frontend, bugfix

#31 Prepare next release
  src/resources/js/app.js
Labels: frontend
